### ISSUE TITLE
shortcut for adding cert option to authenticate with proxied service

### ISSUE THREAD

**Issue by thenewguy** [thomasw/djproxy#19]
It would be convenient if the "cert" kwarg for a client side certificate was exposed like the "verify" kwarg and passed through the call to [self.middleware.process_request](https://github.com/thomasw/djproxy/blob/master/djproxy/views.py#L69).

**Comment by thomasw** [comment]
Yes, definitely. I'm not entirely sure how I missed that. :+1:

**Comment by thomasw** [comment]
The `add_cert_support` branch should add the functionality that you need. Can you do me a favor and give it a try?

**Comment by thenewguy** [comment]
I will make time for this asap.  I was planning to write the PR for this but I've been out of town due to unfortunate circumstances.  I appreciate you getting to it so quickly.  Apologies for my delay.

**Comment by thomasw** [comment]
Ah, no worries, man. I had scheduled time to do a python 3 upgrade on djproxy and just took care of it after I worked through those issues.
