### ISSUE TITLE
bug in HttpProxy.__init__

### ISSUE THREAD

**Issue by pauk-slon** [thomasw/djproxy#24]
Take look at a call of the base class' constructor [here](https://github.com/thomasw/djproxy/blob/master/djproxy/views.py#L37).

    class HttpProxy(View):
        ...
        def __init__(self, *args, **kwargs):
            return super(View, self).__init__(*args, **kwargs)

It must be `return super(HttpProxy, self).__init__(*args, **kwargs)`.

**Comment by thomasw** [comment]
Yikes. Thanks for the report. I'll ship a new version today.
