### ISSUE TITLE
Proxy for dynamic domain

### ISSUE THREAD

**Issue by abuzakaria** [thomasw/djproxy#26]
Is there a way to define reverse proxy for dynamic domain?

**Comment by thomasw** [comment]
Hello! I'm not entirely sure what you mean by dynamic domain?

**Comment by abuzakaria** [comment]
you can delete this issue. as I have modified it for my purpose. thanks for the amazing repo

**Comment by thomasw** [comment]
Ah, cool, I appreciate the thanks. 👍 Hopefully everything works out for you.
