### ISSUE TITLE
configuring proxy to use another proxy

### ISSUE THREAD

**Issue by nimaansary** [thomasw/djproxy#34]
I want to proxy and send ip x.x.x.x requests to y.y.y.y via z.z.z.z proxy!

Can i do this?

**Comment by thomasw** [comment]
Hi @nimaansary, I'm not entirely sure that I fully understand your question but I'll try to help with an example:

* You configure a proxy view for the target y.y.y.y
* You deploy this proxy implementation to z.z.z.z
* A user, x.x.x.x, makes a request to the proxy deployed at z.z.z.z
* The proxy forwards the request to y.y.y.y and returns the result to the user x.x.x.x. To the ultimate target, y.y.y.y, that request will appear to be from z.z.z.z. It will include a header by default, X-Forwarded-For, which identifies the original requestor (x.x.x.x).

Does that help?
