### ISSUE TITLE
base_url same site?

### ISSUE THREAD

**Issue by JoePercipientAI** [thomasw/djproxy#39]
I want to set up a reverse proxy that will proxy a Django app URL to another part of the same website that is outside of Django.

(for example):

www.mysite.com/MyDjangoApp/foo/* -> www.mysite.com/bar/*

And of course, I need this to work for whatever domain/server the app is installed on.

The example in the docs only shows proxying to a static upstream domain (base_url = 'https://google.com/'). How can I set "base_url" in order to use whatever server the original request was made to, instead of always going to a specific domain?

It this isn't specifically configurable, I suppose I could look at request.META['HTTP_HOST'] to find out what server to use, but is there a method that I can hook into where I will have access to the request, and also be able to set base_url at runtime?

**Comment by thomasw** [comment]
Hey Joe, sorry for the delay on this. You should be able to override the behavior of the `proxy_url` property in your subclass.

The original implementation joins the static `base_url` with the url fragment from the URL pattern.

https://github.com/thomasw/djproxy/blob/e7f0c6ef536c01fa8eab193d613ba71406a11cde/djproxy/views.py#L36-L39

In your subclass, you can instead use Django request's built in build_absolute_uri() method to take the proxy fragment and resolve it to a full URL.

```python
class SelfProxy(HttpProxy):
    @property
    def proxy_url(self):
        return self.request.build_absolute_uri(self.kwargs.get('url', ''))
```

IIRC, self.proxy_url is only used in contexts where self.request is set so this should be safe. You can also do this with a middleware, but it's trickier.

**Comment by JoePercipientAI** [comment]
Thanks @thomasw!  Overriding proxy_url worked great!  

One caveat is that even though it won't necessarily be used, you DO have to set `base_url`.  Otherwise, it throws an exception.

**Comment by thomasw** [comment]
Ah, yes:

https://github.com/thomasw/djproxy/blob/e7f0c6ef536c01fa8eab193d613ba71406a11cde/djproxy/views.py#L42

There's some fairly trivial preflight validation to prevent misconfiguration causing exceptions deep in lower level implementation details. You should be able to just set it to `True` or `'NOT_USED_SEE_PROXY_URL'`, ugly as that is.

Never let anyone tell you that you can't proxy yourself. Keep fightin' the good fight.
