### ISSUE TITLE
Headers not passed from upstream to request

### ISSUE THREAD

**Issue by mdathersajjad** [thomasw/djproxy#40]
Forgive me if it's a noob question. I usually code in other programming language. I tried using this library to proxy request but i was getting garbage value in prod which connects to a https url. After struggling i figured out that the headers is not passed from upstream to the proxy request. so i wrote a middle ware and added it to make it work. Is that intentional or bug ?

The middleware looks like this 
```
class AddHeaders(object):

    def process_response(self, proxy, request, upstream_response, response):
        return HttpResponse(response.content, headers=upstream_response.headers)
```

**Comment by thomasw** [comment]
Most headers from the upstream response are automatically sent downstream. You can see the implementation here, which executes right before any middleware:

https://github.com/thomasw/djproxy/blob/e7f0c6ef536c01fa8eab193d613ba71406a11cde/djproxy/views.py#L83-L87

Certain headers are excluded by default though: 

https://github.com/thomasw/djproxy/blob/e7f0c6ef536c01fa8eab193d613ba71406a11cde/djproxy/views.py#L18-L20

It's atypical to forward these headers, but you can disable the filtering behavior by setting ignored_upstream_headers to `[]` in your proxy's configuration. [ref](https://github.com/thomasw/djproxy#httpproxy-configuration)

**Comment by mdathersajjad** [comment]
I think i don't need that custom middleware. thanks @thomasw .
